# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: "Test-goreleaser"
    binary: Test-goreleaser
    env:
    - CGO_ENABLED=0
    flags:
    - -tags=release
    goos:
      - linux
     # - windows
     #- darwin
    goarch:
    - amd64
    ldflags:
    - -s -w
    - -X 'main.version={{.Version}}'
    - -X 'main.commit={{.Commit}}'
    - -X 'main.date={{.Date}}'
    - -X 'main.builtBy=goreleaser'
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: binary
    # Contains only binaries.
    files:
    - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
